src/Entity/Answer.php
<?php

namespace App\Entity;

use App\Repository\AnswerRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AnswerRepository::class)
 * @ORM\Table(name="answers")
 */
class Answer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $answer_text;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="answer")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;

    /**
     * Email
     * @var string
     *
     * @ORM\Column(
     *     type="string",
     *     length=180)
     *
     * @Assert\NotBlank
     * @Assert\Length(
     *     min="10",
     *     max="180",
     * )
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email.",
     *     checkMX = true
     * )
     *
     */
    private $email;

    /**
     * Nick
     * @var string
     *
     * @ORM\Column(
     *     type="string",
     *     length=45
     *     )
     *
     * @Assert\NotBlank
     * @Assert\Length(
     *     min="10",
     *     max="45",
     * )
     */
    private $Nick;

    /**
     * @ORM\Column(type="integer")
     */
    private $isBest;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnswerText(): ?string
    {
        return $this->answer_text;
    }

    public function setAnswerText(string $answer_text): void
    {
        $this->answer_text = $answer_text;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): void
    {
        $this->question = $question;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    public function getNick(): ?string
    {
        return $this->Nick;
    }

    public function setNick(string $Nick): void
    {
        $this->Nick = $Nick;
    }

    public function getIsBest(): ?int
    {
        return $this->isBest;
    }

    public function setIsBest(int $isBest): void
    {
        $this->isBest = $isBest;
    }
}

src/Entity/Question.php
<?php
/**
 * Question Entity
 */
namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Question
 *
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 * @ORM\Table(name="questions")
 */
class Question
{
    /**
     * Primary key
     *
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Subject
     * @var string
     *
     * @ORM\Column(type="string", length=45)
     */
    private $subject;

    /**
     * Text
     * @var string
     * @ORM\Column(type="string", length=200)
     */
    private $text;

    /**
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="question")
     */
    private $answer;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     *
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="questions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function __construct()
    {
        $this->answer = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): void
    {
        $this->subject = $subject;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): void
    {
        $this->text = $text;
    }

    /**
     * @return Collection|Answer[]
     */
    public function getAnswer(): Collection
    {
        return $this->answer;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answer->contains($answer)) {
            $this->answer[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answer->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): void
    {
        $this->category = $category;
    }
}

src/Form/QuestionType.php
<?php
/**
 * Question type.
 */

namespace App\Form;

use App\Entity\Category;
use App\Entity\Question;
use Faker\Provider\Text;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

/**
 * Class QuestionType.
 */
class QuestionType extends AbstractType
{
    /**
     * Builds the form.
     *
     * This method is called for each type in the hierarchy starting from the
     * top most type. Type extensions can further modify the form.
     *
     * @see FormTypeExtensionInterface::buildForm()
     *
     * @param \Symfony\Component\Form\FormBuilderInterface $builder The form builder
     * @param array                                        $options The options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'subject',
            TextType::class,
            [
                'label' => 'label_subject',
                'required' => true,
                'attr' => ['max_length' => 45],
            ]
        );
        $builder->add(
            'text',
            TextType::class,
            [
                'label' => 'label_text',
                'required' => true,
                'attr' => ['max_length' => 200],
            ]
        );
        $builder->add(
            "category",
            EntityType::class,
            [
                'class' => Category::class,
                'choice_label' => function ($category) {
                return $category->getTitle();
                },
                'label' => 'label_category',
                'required' => true,
                'attr' => ['max_length' => 64],
                'empty_data' => '',
                ]
        );
    }

    /**
     * Configures the options for this type.
     *
     * @param \Symfony\Component\OptionsResolver\OptionsResolver $resolver The resolver for the options
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(['data_class' => Question::class]);
    }

    /**
     * Returns the prefix of the template block name for this type.
     *
     * The block prefix defaults to the underscored short class name with
     * the "Type" suffix removed (e.g. "UserProfileType" => "user_profile").
     *
     * @return string The prefix of the template block name
     */
    public function getBlockPrefix(): string
    {
        return 'question';
    }
}

src/Controller/QuestionController.php
<?php
/** Question controller.
 */

namespace App\Controller;

use App\DataFixtures\CategoryFixtures;
use App\Entity\Answer;
use App\Entity\Question;
use App\Entity\User;
use App\Form\AnswerType;
use App\Form\QuestionType;
use App\Repository\AnswerRepository;
use App\Repository\QuestionRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class QuestionController.
 *
 * @Route("/questions")
 */
class QuestionController extends AbstractController
{
    private $questionRepository;
    private $paginator;
    private $answer;
    private $render;
    private $answerRepository;

    /**
     * QuestionsController constructor.
     *
     * @param \App\Component\Pager\PaginatorInterface $paginator
     * @param \App\Repository\QuestionRepository $questionRepository
     */
    public function __construct(QuestionRepository $questionRepository, PaginatorInterface $paginator)
    {
        $this->questionRepository = $questionRepository;
        $this->paginator = $paginator;
    }

    /**
     * Index action.
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/",
     *     methods={"GET"},
     *     name="question_index",
     * )
     */

    public function index(Request $request, QuestionRepository $questionRepository, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $questionRepository->queryAll(),
            $request->query->getInt('page', 1),
            QuestionRepository::PAGINATOR_ITEMS_PER_PAGE
        );

        return $this->render(
            'question/index.html.twig',
            ['pagination' => $pagination]
        );
    }

    /**
     * Show action.
     *
     * @param int $id
     * @param \Symfony\Component\HttpFoundation\Request $request            HTTP request
     * @param \App\Entity\Question $question Question entity
     * @param \App\Entity\Answer $answer Answer entity
     *
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/{id}",
     *     methods={"POST", "GET"},
     *     name="question_show",
     *     requirements={"id": "[1-9]\d*"},
     *)
     *
     */
    public function show(int $id, Request $request, Question $question, AnswerRepository $answerRepository): Response
    {
        $answer = new Answer();
        $form = $this->createForm(AnswerType::class, $answer);
        $form->handleRequest($request);
        $id = $question->getId();

        if ($form->isSubmitted() && $form->isValid()) {
            $answer->setQuestion($question);
            $answerRepository->save($answer);

            return $this->redirectToRoute('question_show', ['id' => $id]);
        }

        $questions = $this->questionRepository->findOneById($id);

        return $this->render(
            'question/show.html.twig',
            ['questions' => $questions, 'answers' => $answerRepository->findAll(), 'form' => $form->createView()]
        );
    }

    /**
     * Create action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request            HTTP request
     * @param \App\Repository\QuestionRepository        $questionRepository Question repository
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @IsGranted("ROLE_ADMIN")
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/create",
     *     methods={"GET", "POST"},
     *     name="question_create",
     * )
     */
    public function create(Request $request): Response
    {
        $question = new Question();
        $form = $this->createForm(QuestionType::class, $question);
        $form->handleRequest($request);

        dump($form);

        if ($form->isSubmitted() && $form->isValid()) {
            $question->setUser($this->getUser());
            $this->questionRepository->save($question);

            return $this->redirectToRoute(('question_index'));
        }

        return $this->render(
            'question/create.html.twig',
            ['form' => $form->createView()]
        );
    }

    /**
     * Edit action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request            HTTP request
     * @param \App\Entity\Category                      $question           Question entity
     * @param \App\Repository\CategoryRepository        $questionRepository Question repository
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @IsGranted("ROLE_ADMIN")
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/{id}/edit",
     *     methods={"GET", "PUT"},
     *     requirements={"id": "[1-9]\d*"},
     *     name="question_edit",
     * )
     */
    public function edit(Request $request, Question $question, QuestionRepository $questionRepository): Response
    {
        $form = $this->createForm(QuestionType::class, $question, ['method' => 'PUT']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $questionRepository->save($question);

            $this->addFlash('success', 'message_updated_successfully');

            return $this->redirectToRoute('question_index');
        }

        return $this->render(
            'question/edit.html.twig',
            [
                'form' => $form->createView(),
                'question' => $question,
            ]
        );
    }

    /**
     * Delete action.
     *
     * @param int $id
     * @param \Symfony\Component\HttpFoundation\Request $request            HTTP request
     * @param \App\Entity\Question                      $question           Question entity
     * @param \App\Repository\QuestionRepository        $questionRepository Question repository
     *
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @IsGranted("ROLE_ADMIN")
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/{id}/delete",
     *     methods={"GET", "DELETE"},
     *     requirements={"id": "[1-9]\d*"},
     *     name="question_delete",
     * )
     */
    public function delete(int $id, Request $request, Question $question, QuestionRepository $questionRepository, AnswerRepository $answerRepository): Response
    {
        $form = $this->createForm(QuestionType::class, $question, ['method' => 'DELETE']);
        $form->handleRequest($request);

        if ($request->isMethod('DELETE') && !$form->isSubmitted()) {
            $form->submit($request->request->get($form->getName()));
        }

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($question->getAnswer() as $answer) {
                $question->removeAnswer($answer);
                $answerRepository->delete($answer);
            }
            $questionRepository->delete($question);


            $this->addFlash('success', 'message.deleted_successfully');

            return $this->redirectToRoute('question_index');
        }

        return $this->render(
            'question/delete.html.twig',
            [
                'form' => $form->createView(),
                'question' => $question,
            ]
        );
    }
}

templates/question/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_question_create'|trans }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_question_create'|trans }}</h1>
    {{ form_start(form, { method: 'POST', action: url('question_create') }) }}
    {{ form_widget(form) }}
    <div class="form-group row float-sm-right">
        <input type="submit" value="{{ 'action_save'|trans }}" class="btn btn-primary" />
    </div>
    <div class="form-group row float-sm-left">
        <a href="{{ url('question_index') }}" class="btn btn-link">
            {{ 'action_back_to_list'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/question/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_question_delete'|trans({'%id%': question.id|default('')}) }}
{% endblock %}

{% block body %}
    <h1 class="display-4 d-flex justify-content-center">{{ 'title_question_delete'|trans({'%id%': question.id|default('')}) }}</h1>
    {{ form_start(form, { method: 'DELETE', action: url('question_delete', {id: question.id}) }) }}
    {{ form_widget(form) }}
    <div class="form-group row float-sm-right">
        <input type="submit" value="{{ 'action_save'|trans }}" class="btn btn-primary" />
    </div>
    <div class="form-group row float-sm-left">
        <a href="{{ url('question_index') }}" class="btn btn-link">
            {{ 'action_back_to_list'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/question/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_question_edit'|trans({'%id%': question.id|default('')}) }}
{% endblock %}

{% block body %}
    <h1 class="display-4 d-flex justify-content-center">{{ 'title_question_edit'|trans({'%id%': question.id|default('')}) }}</h1>
    {{ form_start(form, { method: 'PUT', action: url('question_edit', {id: question.id}) }) }}
    {{ form_widget(form) }}
    <div class="form-group row float-sm-right">
        <input type="submit" value="{{ 'action_save'|trans }}" class="btn btn-primary" />
    </div>
    <div class="form-group row float-sm-left">
        <a href="{{ url('question_index') }}" class="btn btn-link">
            {{ 'action_back_to_list'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/question/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'label_questions_list'|trans }}
{% endblock %}

{% block body %}
    <h1 class="display-4 d-flex justify-content-center">{{ 'label_questions_list'|trans }}</h1>

    {% if is_granted ('ROLE_ADMIN') %}
        <a class="btn btn-outline-success" href="{{ url('question_create') }}" title="{{ 'label_question_create'|trans }}">
            {{ 'label_question_create'|trans }}
        </a>
    {% endif %}

    {% if pagination is defined and pagination.items|length %}

        <div class="navigation text-center">
            {{ knp_pagination_render(pagination) }}
        </div>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'label_question'|trans, 'question.id') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'label_subject'|trans, 'question.subject') }}</th>
                <th>{{ 'label_askedby'|trans }}</th>
                <th>{{ 'label_category'|trans }}</th>
                <th>{{ 'label_actions'|trans }}</th>
            </tr>
            </thead>
            <tbody>

            {% for question in pagination.items %}
                <tr>
                    <td>{{ question.id }}</td>
                    <td>{{ question.subject }}</td>
                    <td>{{ question.user.email }}</td>
                    <td>{{ question.category.title }}</td>
                    <td>
                        <a class="btn btn-info" href="{{ url('question_show', {id: question.id}) }}" title="{{ 'question_view'|trans }}">
                            {{ 'action_view'|trans }}
                        </a>
                        {% if is_granted ('ROLE_ADMIN') %}
                        <a class="btn btn-info" href="{{ url('question_edit', {id: question.id}) }}" title="{{ 'action_edit'|trans }}">
                            {{ 'action_edit'|trans }}
                        </a>
                            <a class="btn btn-info" href="{{ url('question_delete', {id: question.id}) }}" title="{{ 'action_delete'|trans }}">
                                {{ 'action_delete'|trans }}
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="navigation text-center">
            {{ knp_pagination_render(pagination) }}
        </div>

    {% else %}
        {% include 'default/_single_flash_message.html.twig' with {
            type: 'warning',
            message: 'message_empty_list'|trans
        } %}
    {% endif %}
{% endblock  %}

templates/question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'label_question'|trans({'%id%': question.id|default('')}) }} {{ questions.id }}
{% endblock %}

{% block body %}
    <h1 class="display-4 d-flex justify-content-center">{{ 'label_question'|trans({'%id%': question.id|default('')}) }} {{ questions.id }}</h1>
    {% if questions is defined and questions|length %}
        <dl class="dl-horizontal">
            <dt>{{ 'label_subject'|trans }}</dt>
            <dd>{{ questions.subject }}</dd>
            <dt>{{ 'label_question_text'|trans }}</dt>
            <dd>{{  questions.text }}</dd>

            {% if questions.answer|length %}
                <dt class="d-flex p-3">{{ 'label_answers'|trans }}</dt>
            {% endif %}
        </dl>
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>
                        {{ 'answer_text'|trans }}
                    </td>
                    <td>
                        {{ 'label_answeredby'|trans }}
                    </td>
                    <td>
                        {{ '' }}
                    </td>
                    {% if is_granted ('ROLE_ADMIN') %}
                    <td>
                        {{ 'label_action'|trans }}
                    </td>
                    {% endif %}
                </tr>
                </thead>
                {% for answer in answers %}
                    <tr>
                        {% if answer.question.id == questions.id and answer.isBest == 1 %}
                        <td>
                            {{ answer.answertext }}
                        </td>
                        <td>
                            {{ answer.nick }}
                        </td>
                        <td class="table-success" >
                            {{ 'best_answer'|trans }}
                        </td>
                            <td>
                                {% if is_granted ('ROLE_ADMIN') %}
                                    <a class="btn btn-info" href="{{ url('answer_edit', {id: answer.id}) }}" title="{{ 'label_answer_edit'|trans }}">
                                        {{ 'label_answer_edit'|trans }}
                                    </a>
                                    <a class="btn btn-info" href="{{ url('answer_delete', {id: answer.id}) }}" title="{{ 'label_answer_delete'|trans }}">
                                        {{ 'label_answer_delete'|trans }}
                                    </a>
                                    <a class="btn btn-info" href="{{ url('answer_best', {id: answer.id}) }}" title="{{ 'label_answer_isBest'|trans }}">
                                        {{ 'label_answer_isBest'|trans }}
                                    </a>
                                {% endif %}
                            </td>

                        {% endif %}
                    </tr>
                {% endfor %}

                {% for answer in answers %}
                <tr>
                    {% if answer.question.id == questions.id and answer.isBest == 0  %}
                        <td>
                            {{ answer.answertext }}
                        </td>
                        <td>
                            {{ answer.nick }}
                        </td>
                        <td>
                            {{ '' }}
                        </td>
                        <td>
                            {% if is_granted ('ROLE_ADMIN') %}

                            <a class="btn btn-info" href="{{ url('answer_edit', {id: answer.id}) }}" title="{{ 'label_answer_edit'|trans }}">
                                {{ 'label_answer_edit'|trans }}
                            </a>
                            <a class="btn btn-info" href="{{ url('answer_delete', {id: answer.id}) }}" title="{{ 'label_answer_delete'|trans }}">
                                {{ 'label_answer_delete'|trans }}
                            </a>
                            <a class="btn btn-info" href="{{ url('answer_best', {id: answer.id}) }}" title="{{ 'label_answer_isBest'|trans }}">
                                {{ 'label_answer_isBest'|trans }}
                            </a>

                            {% endif %}
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>

        <p>

            <button class="btn btn-outline-success" type="button" data-toggle="collapse" data-target="#collapseForm" aria-expanded="false" aria-controls="collapseForm">
                {{ 'label_answer_create'|trans }}
            </button>

        <div id="collapseForm" class="collapse">
            {{ form_start(form) }}
            {{ form_widget(form) }}

            <div  class="float-sm-right p-3">
                <input type="submit" value="{{ 'save'|trans }}" class="btn btn-info row">
            </div>

            {{ form_end(form) }}
        </div>
        <br>
        <br>
        <br>
        <div>
        <p>
            <a class="btn btn-info" href="{{ url('question_index') }}" title="{{ 'action_back_to_list'|trans }}">
                {{ 'action_back_to_list'|trans }}
            </a>
        </p>
        </div>

    {% else %}
        <p>
            {{ 'message_item_not_found'|trans }}
        </p>
    {% endif %}
{% endblock %}